Repository xiph/rav1e, pull requests merged in 2018-12, with the labels that each got.

#799 Add rate of partition type in RDO decision
  src/rdo.rs
Labels: bug, difficult

#707 [WIP] Add horz/vert (2:1 only) partitions to top-down partition rdo
  src/context.rs
  src/encoder.rs
  src/partition.rs
  src/rdo.rs
Labels: WorkInProgress

#813 Refactor duplicated code block in bottomup partition rdo
  src/encoder.rs
  src/rdo.rs
Labels: code cleanup

#814 Better name for the encode_block_helper1()
  src/encoder.rs
  src/rdo.rs
Labels: code beautification

#816 Enable rectangular partitions with bottomup rdo partition search
  src/encoder.rs
  src/partition.rs
  src/rdo.rs
Labels: WorkInProgress, enhancement
