Repository xiph/rav1e, pull requests merged in 2018-10, with the labels that each got.

#636 Add a function to produce a container-compatible sequence header
  src/api.rs
Labels: enhancement

#649 Rudimentary port of av1_scan_orders to rust.
  src/context.rs
  src/lib.rs
  src/scan_order.rs
Labels: hacktoberfest

#660 Port default_nmv_context to rust
  src/context.rs
  src/lib.rs
Labels: hacktoberfest

#664 Remove C dependency from transform.rs
  README.md
  rustfmt.toml
  src/partition.rs
  src/transform.rs
  src/transform/forward.rs
  src/transform/inverse.rs
  src/transform/mod.rs
Labels: enhancement, hacktoberfest

#669 Port the entropy decoder in libaom to rust
  src/ec.rs
Labels: hacktoberfest

#680 Transform domain distortion for RDO-based mode decision
  benches/bench.rs
  src/encoder.rs
  src/quantize.rs
  src/rdo.rs
Labels: enhancement

#673 Hierarchical motion estimation
  src/api.rs
  src/context.rs
  src/encoder.rs
  src/me.rs
  src/partition.rs
  src/plane.rs
  src/rdo.rs
Labels: WorkInProgress

#685 Use macro for libaom bindings in intra pred tests
  src/predict.rs
Labels: hacktoberfest
