Repository xiph/rav1e, pull requests merged in 2018-11, with the labels that each got.

#697 Draft: add tests for transforms
  src/transform/mod.rs
Labels: WorkInProgress, hacktoberfest

#719 Enable 2:1 and 4:1 rectangular intra prediction function calls"
  src/partition.rs
  src/predict.rs
Labels: conformance, easy

#741 [WIP] Fix quantize() for rectangular tx with 64 pels as either dimension
  src/context.rs
  src/encoder.rs
  src/quantize.rs
Labels: WorkInProgress

#740 Add 14 rectangular tx functions
  src/partition.rs
  src/transform/forward.rs
  src/transform/inverse.rs
  src/transform/mod.rs
Labels: WorkInProgress, conformance

#746 Fix pred_dc_left() to use height to index left ref
  src/predict.rs
Labels: bug, conformance

#745 Fix get_tx_set() for rectangular tx_sizes > 32x32
  src/context.rs
  src/encoder.rs
Labels: bug, conformance

#749 Fix the part of fixes in ecb01d413d9
  src/context.rs
Labels: bug

#748 Fix for 32x16, 32x8, etc. rect tx functions to have idtx tx_type as well
  src/transform/forward.rs
Labels: bug, conformance

#751 Counterpart fix for inv with 70477dc9
  src/transform/inverse.rs
Labels: bug

#754 Remove obsolete function y_intra_mode_to_tx_type_context()
  src/context.rs
Labels: code cleanup

#756 Fix get_log_tx_scale() for rectangular transforms
  src/quantize.rs
Labels: conformance

#769 Change the default key frame interval from 30 to 60
  src/api.rs
  src/bin/common.rs
Labels: enhancement, good first issue

#763 Adaptive keyframe selection
  src/api.rs
  src/bin/common.rs
  src/encoder.rs
  src/lib.rs
  src/scenechange/mod.rs
  src/test_encode_decode.rs
Labels: WorkInProgress, research

#774 Fix that number of rows is used for vertical 1d tx in inverse tx
  src/transform/inverse.rs
Labels: bug

#775 Fix missing inv sqrt2 factor for rect inv tx
  src/transform/inverse.rs
  src/transform/mod.rs
Labels: bug
