Repository xiph/rav1e, pull requests merged in 2019-01, with the labels that each got.

#839 Optionally use dav1d in the encode-decode tests
  Cargo.toml
  src/encoder.rs
  src/lib.rs
  src/test_encode_decode_aom.rs
  src/test_encode_decode_dav1d.rs
Labels: WorkInProgress

#858 Early termination for bottomup partition search (i.e. speed 0 only)
  src/encoder.rs
Labels: enhancement

#864 Add and hookup inverse txfm assembly
  build.rs
  src/transform/inverse.rs
  src/transform/mod.rs
  src/x86/itx.asm
Labels: enhancement

#861 Deduplicate checkpoint() calls in rdo_partition_decision()
  src/rdo.rs
Labels: enhancement

#859 Early termination for topdown partition search
  src/rdo.rs
Labels: WorkInProgress, enhancement

#883 Improve bottomup partition code 0
  src/encoder.rs
Labels: WorkInProgress, enhancement

#889 The rdo_mode_decision() only returns RDOPartitionOutput struct
  src/encoder.rs
  src/rdo.rs
Labels: code beautification, code cleanup

#897 Fix update_partition_context() to be not called for rect partition
  src/context.rs
  src/encoder.rs
Labels: bug
