Repository xiph/rav1e, pull requests merged in 2019-05, with the labels that each got.

#1264 Turn off enable_filter_intra in sequence header
  src/encoder.rs
  src/header.rs
Labels: compression performance

#1278 Rename inter dedicated mode_set in rdo
  src/rdo.rs
Labels: code cleanup

#1284 Rename 'rdo_use_only' function parameters as 'use_recon_pixel'
  benches/bench.rs
  src/encoder.rs
  src/rdo.rs
Labels: better naming, code beautification

#1277 Fix rec pixels not computed when tx is smaller than block
  src/encoder.rs
  src/rdo.rs
Labels: bug

#1288 Add trial encodes for first frame of each type
  src/api.rs
  src/rate.rs
Labels: high priority, research
