Repository xiph/rav1e, pull requests merged in 2020-08, with the labels that each got.

#2479 CI (js_api.yml): Fix wasm-pack build
  .github/workflows/js_api.yml
Labels: CI

#2480 Jsapi update ci
  .github/workflows/js_api.yml
Labels: CI

#2488 Fix tx size context update for skipped intra block
  src/context/block_unit.rs
Labels: bug

#2493 rav1e_js: Various small changes
  rav1e_js/Cargo.toml
  rav1e_js/src/encoder/frame_encoder.rs
  rav1e_js/src/encoder/video_encoder.rs
  rav1e_js/src/lib.rs
  rav1e_js/tests/utils.rs
Labels: enhancement
